### ISSUE TITLE
potential hard to debug issue that leads to a false positive with mocha & promise based API

### ISSUE THREAD

**Issue by alexjeffburke** [unexpectedjs/unexpected-express#4]
Hi there,

I think a potential footgun has been created with the promisified version of the library when used with mocha. I didn't quite understand the importance of the return (I had no idea that you could return a promise and mocha would latch onto it) in the example it() block so I left it off at first. I also left out a 'done' parameter to the function I passed to it().

In unexpected-express 5.0.4, leaving off the done would have resulted in an exception that would immediately alert the user to the problem. However, as originally written the test passed, I got a false positive but the assertions had even been run. My suggestion, to catch this case, would be to throw an exception if no done was attached to the promise. I noticed that a bunch of then() blocks are used inside the code?

I wonder if it would be possible to store the count of the callback and assert if did not increase? That, or if that's over-engineering then maybe mention it explicitly in the docs. I also wonder if the version of mocha would matter?

At any rate, hope this helps. Alex J Burke.

**Comment by sunesimonsen** [comment]
Hi @alexjeffburke, don't you get an unhandled rejection error when the promise fails?

You can also use this construct if you what complete safety.
http://unexpectedjs.github.io/api/async/

**Comment by alexjeffburke** [comment]
Hey,

So, I accidentally had something like this:
    it('should handle a simple request', function () {
        expect(middleware, 'to yield exchange', {
            request: {
                url: '/'
            },
            response: {
                statusCode: 200
            }
        });
    });

The middleware was not returning success, but mocha is saying there was one test that passed - no exception occurred. I'll take a peek at that async stuff in bit :)

Thanks!

**Comment by sunesimonsen** [comment]
That sounds bad, you should get an unhandled rejection. We will look into it. - thanks.

**Comment by sunesimonsen** [comment]
@alexjeffburke sorry expect.async had an error that means the error message would not be serialized. I'm fixing that.

**Comment by alexjeffburke** [comment]
Cool & no probs, glad I could help :)

**Comment by sunesimonsen** [comment]
If you upgrade to unexpected 7.0.1 expect.async is fixed.

**Comment by papandreou** [comment]
Our previous experiments indicated that a missing `return` without the `expect.async` construct would still result in mocha reporting an uncaught error and exiting with non-zero. However, a test suite only containing your example with the missing return, the test is marked as passing. That's really bad -- the worst kind of error.

I just took a brief look at https://github.com/domenic/chai-as-promised/, but it looks like that library doesn't do anything to address the situation either.

A really good solution where the error is reported in the context of the test that commits the missing `return` sin will probably require us to blur the line separating the test framework from the assertion lib a bit.

**Comment by alexjeffburke** [comment]
Really appreciate you guys looking into this, I was also just about to report updating the 7.0.1 did not fix the problem here sadly.

@papandreou yeah I agree - I know it might be a tricky one to fix, but a false positive (however it happens) is a really nasty situation when you're dealing with testing code.

I did have a look inside unexpected-express (you guys have been busy!) and noticed that it uses a promise internally. I'm not at all saying I understand the intricacies in there, but @sunesimonsen mentioned an unhanded rejection error.. perhaps handing out a fresh promise that is resolved by the others would trigger an exception if nothing was attached to it? I just fear that might happen *after* mocha marks the it() block successful and you'd get the exception occur later (nasty but might give you a chance of taking it down).

**Comment by sunesimonsen** [comment]
@alexjeffburke I made a spike on detecting the situation here: https://github.com/unexpectedjs/unexpected/tree/spike/wrappedIt
could you try to like it and see if it works.

Did v7.0.1 in combination with expect.async not report anything?

**Comment by alexjeffburke** [comment]
Boom! This is what I got after an npm link of that branch:
  'Error: When using asynchronous assertions you must return a promise from the it block'

Ah sorry, I misunderstood what you meant - I tried expect.async and it did print the following (I did not add the newline after Error):
     Error: 
expect.async requires the block to return a promise or throw an exception

But, if I read it correctly, that latches onto the 'done' so would likely mask the issue a bit as at minimum mocha becomes aware it's expecting something async in that case.

I had a peek at what you did to fix it.. can see what @papandreou meant about having to blur the lines a bit. Let me know what you decide to do :)

**Comment by papandreou** [comment]
> can see what @papandreou meant about having to blur the lines a bit. Let me know what you decide to do :)

https://github.com/mochajs/mocha/issues/1651#issuecomment-96419044

**Comment by alexjeffburke** [comment]
Cool - interesting that mocha may be considering such a thing.

Meantime I noticed that the fix I tested is on track to become part of unexpected 8 - I'll leave this open until that is released, test it then close it.

**Comment by papandreou** [comment]
Footgun disarmed in Unexpected 8.0.0, which was just released along with unexpected-express 7.0.1.
